version: '3.8'  # Указываем версию файла Docker Compose

services:
  java-app:
    image: openjdk:21-jdk-slim
    container_name: java_h2_app
    ports:
      - "8080:8080"       # Порт для веб-приложения
      - "9093:9093"       # Другой порт, возможно для API или админки
    volumes:
      - ./target:/app     # Монтирование локальной папки /target в контейнер
    command: java -jar /app/shareit-0.0.1-SNAPSHOT.jar  # Запуск JAR-файла
    environment:
      H2_DB_URL: jdbc:h2:tcp://h2:9092/mem:testdb  # URL базы данных
      H2_DB_USER: sa
      H2_DB_PASSWORD: password
    depends_on:
      - h2  # Указывает, что контейнер зависит от контейнера h2

  h2:
    image: oscarfonts/h2:2.1.214
    container_name: h2
    ports:
      - "9092:9092"  # Порт для TCP подключения к базе
      - "8083:8082"  # Порт для H2 веб-консоли
    environment:
      H2_OPTIONS: -web -webAllowOthers -tcp -tcpAllowOthers -tcpPort 9092  # Настройки H2
    volumes:
      - h2-data:/opt/h2-data  # Создается том для хранения данных H2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]  # Проверка стабильности сервиса
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  h2-data:  # Объявляем том для хранения данных H2