DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS item_requests CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    user_email VARCHAR(512) NOT NULL UNIQUE
);

CREATE TABLE item_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_description VARCHAR(512) NOT NULL,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(255) NOT NULL,
    item_description VARCHAR(512),
    item_available BOOLEAN NOT NULL,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    request_id BIGINT REFERENCES item_requests(request_id) ON DELETE SET NULL
);

CREATE TABLE bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    booking_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT REFERENCES items(item_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(512) NOT NULL,
    item_id BIGINT REFERENCES items(item_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_users_email ON users(user_email);
CREATE INDEX idx_items_owner ON items(user_id);
CREATE INDEX idx_items_available ON items(item_available);
CREATE INDEX idx_items_request ON items(request_id);
CREATE INDEX idx_bookings_dates ON bookings(booking_start, booking_end);
CREATE INDEX idx_bookings_status ON bookings(status);
CREATE INDEX idx_bookings_user ON bookings(user_id);
CREATE INDEX idx_bookings_item ON bookings(item_id);
CREATE INDEX idx_requests_user ON item_requests(user_id);
CREATE INDEX idx_comments_item ON comments(item_id);
CREATE INDEX idx_comments_user ON comments(user_id);

