server.port=8080

spring.cloud.gateway.routes[0].id=users
spring.cloud.gateway.routes[0].uri=http://server:9090
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[1].id=items
spring.cloud.gateway.routes[1].uri=http://server:9090
spring.cloud.gateway.routes[1].predicates[0]=Path=/items/**

spring.cloud.gateway.routes[2].id=bookings
spring.cloud.gateway.routes[2].uri=http://server:9090
spring.cloud.gateway.routes[2].predicates[0]=Path=/bookings/**

spring.cloud.gateway.routes[3].id=requests
spring.cloud.gateway.routes[3].uri=http://server:9090
spring.cloud.gateway.routes[3].predicates[0]=Path=/requests/**
